"""Add is_weight_based to OrderItem

Revision ID: 41dfe6336a35
Revises: 7474af73fd09
Create Date: 2026-06-30 13:10:28.102664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41dfe6336a35'
down_revision: Union[str, Sequence[str], None] = '7474af73fd09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('is_weight_based', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'is_weight_based')
    # ### end Alembic commands ###
