"""module1_location_and_charges

Revision ID: 42832b896d04
Revises: e33d98848be2
Create Date: 2026-06-25 00:55:26.797533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.engine.reflection import Inspector

def column_exists(table_name, column_name):
    bind = op.get_context().bind
    insp = Inspector.from_engine(bind)
    has_table = insp.has_table(table_name)
    if not has_table:
        return False
    columns = [c['name'] for c in insp.get_columns(table_name)]
    return column_name in columns


# revision identifiers, used by Alembic.
revision: str = '42832b896d04'
down_revision: Union[str, Sequence[str], None] = 'e33d98848be2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    if not column_exists('orders', 'customer_latitude'):
        op.add_column('orders', sa.Column('customer_latitude', sa.Float(), nullable=True))
    if not column_exists('orders', 'customer_longitude'):
        op.add_column('orders', sa.Column('customer_longitude', sa.Float(), nullable=True))
    if not column_exists('orders', 'delivery_distance_km'):
        op.add_column('orders', sa.Column('delivery_distance_km', sa.Float(), nullable=True))
    if not column_exists('orders', 'subtotal'):
        op.add_column('orders', sa.Column('subtotal', sa.Float(), nullable=False, server_default='0.0'))
    if not column_exists('orders', 'delivery_charge'):
        op.add_column('orders', sa.Column('delivery_charge', sa.Float(), nullable=False, server_default='0.0'))
    if not column_exists('orders', 'handling_charge'):
        op.add_column('orders', sa.Column('handling_charge', sa.Float(), nullable=False, server_default='0.0'))
    if not column_exists('settings', 'store_latitude'):
        op.add_column('settings', sa.Column('store_latitude', sa.Float(), nullable=True))
    if not column_exists('settings', 'store_longitude'):
        op.add_column('settings', sa.Column('store_longitude', sa.Float(), nullable=True))
    if not column_exists('settings', 'free_delivery_radius_km'):
        op.add_column('settings', sa.Column('free_delivery_radius_km', sa.Float(), nullable=True))
    if not column_exists('settings', 'max_delivery_radius_km'):
        op.add_column('settings', sa.Column('max_delivery_radius_km', sa.Float(), nullable=True))
    if not column_exists('settings', 'delivery_charges_enabled'):
        op.add_column('settings', sa.Column('delivery_charges_enabled', sa.Boolean(), nullable=True))
    if not column_exists('settings', 'delivery_charge_model'):
        op.add_column('settings', sa.Column('delivery_charge_model', sa.String(), nullable=True))
    if not column_exists('settings', 'flat_delivery_fee'):
        op.add_column('settings', sa.Column('flat_delivery_fee', sa.Float(), nullable=True))
    if not column_exists('settings', 'delivery_charge_per_km'):
        op.add_column('settings', sa.Column('delivery_charge_per_km', sa.Float(), nullable=True))
    if not column_exists('settings', 'handling_charge'):
        op.add_column('settings', sa.Column('handling_charge', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'handling_charge')
    op.drop_column('settings', 'delivery_charge_per_km')
    op.drop_column('settings', 'flat_delivery_fee')
    op.drop_column('settings', 'delivery_charge_model')
    op.drop_column('settings', 'delivery_charges_enabled')
    op.drop_column('settings', 'max_delivery_radius_km')
    op.drop_column('settings', 'free_delivery_radius_km')
    op.drop_column('settings', 'store_longitude')
    op.drop_column('settings', 'store_latitude')
    op.drop_column('orders', 'handling_charge')
    op.drop_column('orders', 'delivery_charge')
    op.drop_column('orders', 'subtotal')
    op.drop_column('orders', 'delivery_distance_km')
    op.drop_column('orders', 'customer_longitude')
    op.drop_column('orders', 'customer_latitude')
    # ### end Alembic commands ###
