"""module2_weight_based_inventory

Revision ID: 7474af73fd09
Revises: 8727e7cb0564
Create Date: 2026-06-30 12:54:35.006150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7474af73fd09'
down_revision: Union[str, Sequence[str], None] = '8727e7cb0564'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('is_weight_based', sa.Boolean(), nullable=True))
    op.add_column('products', sa.Column('available_stock', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('low_stock_threshold', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'is_active')
    op.drop_column('products', 'low_stock_threshold')
    op.drop_column('products', 'available_stock')
    op.drop_column('products', 'is_weight_based')
    # ### end Alembic commands ###
