"""Add tracking_token to Order

Revision ID: 7535664f2e3f
Revises: 7e0e1909f968
Create Date: 2026-07-04 17:47:23.702193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.engine.reflection import Inspector

def column_exists(table_name, column_name):
    bind = op.get_context().bind
    insp = Inspector.from_engine(bind)
    has_table = insp.has_table(table_name)
    if not has_table:
        return False
    columns = [c['name'] for c in insp.get_columns(table_name)]
    return column_name in columns


# revision identifiers, used by Alembic.
revision: str = '7535664f2e3f'
down_revision: Union[str, Sequence[str], None] = '7e0e1909f968'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    if not column_exists('orders', 'tracking_token'):
        op.add_column('orders', sa.Column('tracking_token', sa.String(), nullable=True))
    op.create_index(op.f('ix_orders_tracking_token'), 'orders', ['tracking_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_tracking_token'), table_name='orders')
    op.drop_column('orders', 'tracking_token')
    # ### end Alembic commands ###
