"""Add razorpay payment fields to order

Revision ID: 7e0e1909f968
Revises: 41dfe6336a35
Create Date: 2026-07-04 14:35:30.679547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.engine.reflection import Inspector

def column_exists(table_name, column_name):
    bind = op.get_context().bind
    insp = Inspector.from_engine(bind)
    has_table = insp.has_table(table_name)
    if not has_table:
        return False
    columns = [c['name'] for c in insp.get_columns(table_name)]
    return column_name in columns


# revision identifiers, used by Alembic.
revision: str = '7e0e1909f968'
down_revision: Union[str, Sequence[str], None] = '41dfe6336a35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    if not column_exists('orders', 'payment_method'):
        op.add_column('orders', sa.Column('payment_method', sa.String(), nullable=True))
    if not column_exists('orders', 'payment_status'):
        op.add_column('orders', sa.Column('payment_status', sa.String(), nullable=True))
    if not column_exists('orders', 'razorpay_order_id'):
        op.add_column('orders', sa.Column('razorpay_order_id', sa.String(), nullable=True))
    if not column_exists('orders', 'razorpay_payment_id'):
        op.add_column('orders', sa.Column('razorpay_payment_id', sa.String(), nullable=True))
    if not column_exists('orders', 'razorpay_signature'):
        op.add_column('orders', sa.Column('razorpay_signature', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'razorpay_signature')
    op.drop_column('orders', 'razorpay_payment_id')
    op.drop_column('orders', 'razorpay_order_id')
    op.drop_column('orders', 'payment_status')
    op.drop_column('orders', 'payment_method')
    # ### end Alembic commands ###
