"""add_gmaps_link_to_settings

Revision ID: 8727e7cb0564
Revises: 88a8d6fa14b9
Create Date: 2026-06-27 03:12:34.824847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.engine.reflection import Inspector

def column_exists(table_name, column_name):
    bind = op.get_context().bind
    insp = Inspector.from_engine(bind)
    has_table = insp.has_table(table_name)
    if not has_table:
        return False
    columns = [c['name'] for c in insp.get_columns(table_name)]
    return column_name in columns


# revision identifiers, used by Alembic.
revision: str = '8727e7cb0564'
down_revision: Union[str, Sequence[str], None] = '88a8d6fa14b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    if not column_exists('settings', 'gmaps_link'):
        op.add_column('settings', sa.Column('gmaps_link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'gmaps_link')
    # ### end Alembic commands ###
