"""Add structured address fields to orders

Revision ID: 88a8d6fa14b9
Revises: 42832b896d04
Create Date: 2026-06-25 02:16:30.263694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.engine.reflection import Inspector

def column_exists(table_name, column_name):
    bind = op.get_context().bind
    insp = Inspector.from_engine(bind)
    has_table = insp.has_table(table_name)
    if not has_table:
        return False
    columns = [c['name'] for c in insp.get_columns(table_name)]
    return column_name in columns


# revision identifiers, used by Alembic.
revision: str = '88a8d6fa14b9'
down_revision: Union[str, Sequence[str], None] = '42832b896d04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    if not column_exists('orders', 'house_no'):
        op.add_column('orders', sa.Column('house_no', sa.String(), nullable=True))
    if not column_exists('orders', 'street'):
        op.add_column('orders', sa.Column('street', sa.String(), nullable=True))
    if not column_exists('orders', 'landmark'):
        op.add_column('orders', sa.Column('landmark', sa.String(), nullable=True))
    if not column_exists('orders', 'city'):
        op.add_column('orders', sa.Column('city', sa.String(), nullable=True))
    if not column_exists('orders', 'pincode'):
        op.add_column('orders', sa.Column('pincode', sa.String(), nullable=True))
    if not column_exists('orders', 'delivery_notes'):
        op.add_column('orders', sa.Column('delivery_notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'delivery_notes')
    op.drop_column('orders', 'pincode')
    op.drop_column('orders', 'city')
    op.drop_column('orders', 'landmark')
    op.drop_column('orders', 'street')
    op.drop_column('orders', 'house_no')
    # ### end Alembic commands ###
